### ISSUE TITLE
请问你是用哪个分支哪个版本编译的？

### ISSUE THREAD

**Issue by huijiawanquba** [wanliyang1990/WliveTV#7]
请问你是用哪个分支哪个版本编译的？

**Comment by wanliyang1990** [comment]
这个ijk是很老的版本了 你可以试试这个库：https://github.com/wanliyang1990/wlmedia

**Comment by huijiawanquba** [comment]
我用新版本的ijkplayer编译，发现高清ts视频出现音视频不同步的情况，请问你知道怎么回事吗？用你这个版本的库播放同步没问题，但是播放非高清的出现黑屏有声音的现象，不知道你用的哪个分支的版本？

**Comment by wanliyang1990** [comment]
具体我忘了 你看看15年的版本 然后 高清ts流不同步 你是不是没有开启硬解码

**Comment by huijiawanquba** [comment]
配置是这样的：
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
                        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 1);
                        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 1);
                        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1);
                        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "start-on-prepared", 0);
                        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "http-detect-range-support", 0);
                        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);

应该没啥问题吧？搜到了其他人的也是这个版本，播放挺好的，也是黑屏有声音，不知道啥情况。

**Comment by wanliyang1990** [comment]
新版本的IJK我也没有使用过 具体不清楚 现在都是自己基于ffmpeg写播放器，你先用这个https://github.com/wanliyang1990/wlmedia 试试 看看能正常播放不呢

**Comment by huijiawanquba** [comment]
谢谢你，刚才试了一下，可以播放，但是卡顿严重，不知道咋回事。
